/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Dao.CourseDao;
import Dao.StudentDao;
import Dao.TutorDao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Course;
import model.Tutor;

/**
 *
 * @author Celia
 */
  
public class TutorForm extends javax.swing.JFrame {

DefaultTableModel tableModel = new DefaultTableModel();
String email;
String tutor;

//int tutor_id;
//TutorDao dao = new TutorDao();
    private void initCourseComboBox() {
    //dao.populateCourseComboBox(courseNameTxt);
   studCourse();
    }
    
    private void studCourse(){
      TutorDao dao=new TutorDao();
        List<Course> courses=dao.allCourses();
        if(courses!=null){
            
            for(Course stcourse: courses){
            courseNameTxt.addItem(String.valueOf(stcourse.getCourseName()));
            
       }
    }
    }
    /**
     * Creates new form tutorForm
     */
    String gender;
    String courseName;
    public TutorForm() {
        initComponents();
        initCourseComboBox();
        addTableColumn();
        addTableRowData();
        
    }
    
    private void addTableColumn(){
        tableModel.addColumn("Tutor ID");
        tableModel.addColumn("Full Name");
        tableModel.addColumn("Gender");
        tableModel.addColumn("Email");
        tableModel.addColumn("Course Name");
        
        tutorTable.setModel(tableModel);
    }
    private void addTableRowData(){
        tableModel.setRowCount(0);
        TutorDao dao= new TutorDao();
        //List<Tutor> tutors = dao.allCourses();
        List<Tutor> tutors = dao.allTutors();
        for(Tutor theTutor : tutors){
            tableModel.addRow(new Object[]{
                theTutor.getTutorId(),
                theTutor.getFullName(),
                theTutor.getGender(),
                theTutor.getEmail(),
                theTutor.getCourseName()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fullNameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JPasswordField();
        genderCombo = new javax.swing.JComboBox<>();
        tutoregisterBtn = new javax.swing.JButton();
        loginLink = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        courseNameTxt = new javax.swing.JComboBox<>();
        logoutLink = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        idtxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tutorTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        previousPageLink = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        updateBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        fullNameSearchTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        refreshbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 30)); // NOI18N
        jLabel1.setText("Tutor Registration Form");

        jLabel2.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel2.setText("Full Name:");

        fullNameTxt.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel3.setText("Gender");

        jLabel4.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel5.setText("Course:");

        jLabel6.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        jLabel6.setText("Password:");

        genderCombo.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        genderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        genderCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                genderComboMouseClicked(evt);
            }
        });

        tutoregisterBtn.setBackground(java.awt.SystemColor.textHighlight);
        tutoregisterBtn.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        tutoregisterBtn.setText("Register");
        tutoregisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutoregisterBtnActionPerformed(evt);
            }
        });

        loginLink.setFont(new java.awt.Font("Mongolian Baiti", 1, 14)); // NOI18N
        loginLink.setForeground(new java.awt.Color(51, 51, 255));
        loginLink.setText("Already have an account? Login");
        loginLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginLinkMouseClicked(evt);
            }
        });

        emailTxt.setFont(new java.awt.Font("Mongolian Baiti", 0, 18)); // NOI18N

        courseNameTxt.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        courseNameTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                courseNameTxtMouseClicked(evt);
            }
        });
        courseNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseNameTxtActionPerformed(evt);
            }
        });

        logoutLink.setFont(new java.awt.Font("Mongolian Baiti", 1, 14)); // NOI18N
        logoutLink.setForeground(new java.awt.Color(51, 51, 255));
        logoutLink.setText("Logout");
        logoutLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLinkMouseClicked(evt);
            }
        });

        jPanel2.setBackground(java.awt.SystemColor.textHighlight);
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutLink)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(courseNameTxt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(passwordTxt)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(genderCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(emailTxt)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(fullNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(91, 91, 91))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(loginLink))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(tutoregisterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(fullNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(courseNameTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(tutoregisterBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginLink)
                .addGap(18, 18, 18)
                .addComponent(logoutLink)
                .addGap(4, 4, 4)
                .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        tutorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tutorTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tutorTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tutorTable);

        jLabel7.setFont(new java.awt.Font("Mongolian Baiti", 1, 30)); // NOI18N
        jLabel7.setText("Tutors List");

        previousPageLink.setFont(new java.awt.Font("Mongolian Baiti", 1, 14)); // NOI18N
        previousPageLink.setForeground(new java.awt.Color(51, 51, 255));
        previousPageLink.setText("<Go to previous page");
        previousPageLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previousPageLinkMouseClicked(evt);
            }
        });

        logoutBtn.setBackground(java.awt.SystemColor.textHighlight);
        logoutBtn.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jPanel4.setBackground(java.awt.SystemColor.textHighlight);
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        updateBtn.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jLabel8.setText("Enter the tutor Full Name:");

        searchBtn.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        refreshbtn.setFont(new java.awt.Font("Mongolian Baiti", 1, 24)); // NOI18N
        refreshbtn.setText("Refresh");
        refreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fullNameSearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(searchBtn)
                                .addGap(29, 29, 29)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutBtn)
                .addGap(277, 277, 277))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(previousPageLink)
                        .addGap(263, 263, 263))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(updateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refreshbtn)
                        .addGap(63, 63, 63))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fullNameSearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchBtn)))
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBtn)
                    .addComponent(refreshbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(previousPageLink)
                .addGap(113, 113, 113))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tutoregisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutoregisterBtnActionPerformed
        if(fullNameTxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Full Name is Mandatory","Mandatory Field",JOptionPane.WARNING_MESSAGE);
        }else if(genderCombo.getSelectedItem().toString().isEmpty()){
            JOptionPane.showMessageDialog(null, "Gender is Mandatory","Mandatory Field",JOptionPane.WARNING_MESSAGE);
        }else if(emailTxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Email is Mandatory","Mandatory Field",JOptionPane.WARNING_MESSAGE);
        }else if(courseNameTxt.getSelectedItem().toString().isEmpty()){
            JOptionPane.showMessageDialog(null, "Course Name is Mandatory","Mandatory Field",JOptionPane.WARNING_MESSAGE);
        }else if(passwordTxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Password is Mandatory","Mandatory Field",JOptionPane.WARNING_MESSAGE);
        }
        
        Tutor theTutor = new Tutor();
        theTutor.setFullName(fullNameTxt.getText());
        theTutor.setGender(gender);
        theTutor.setEmail(emailTxt.getText());
        theTutor.setCourseName(courseName);
        theTutor.setPassword(passwordTxt.getText());
        
        TutorDao dao = new TutorDao();
        String gender = genderCombo.getSelectedItem().toString();
        String courseName = courseNameTxt.getSelectedItem().toString();
        String feedback = dao.registerTutor(theTutor, gender, courseName);
        JOptionPane.showMessageDialog(this, feedback);
        
        fullNameTxt.setText(""); 
        genderCombo.setSelectedItem("");
        emailTxt.setText("");
        courseNameTxt.setSelectedItem("");
        passwordTxt.setText("");
        addTableRowData();
        
    }//GEN-LAST:event_tutoregisterBtnActionPerformed

    private void genderComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genderComboMouseClicked
        // TODO add your handling code here:
        gender = genderCombo.getSelectedItem().toString();
        
    }//GEN-LAST:event_genderComboMouseClicked

    private void courseNameTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseNameTxtMouseClicked
        //courseName = courseNameTxt.getSelectedItem().toString();
        
    }//GEN-LAST:event_courseNameTxtMouseClicked

    private void loginLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLinkMouseClicked
        StudTutorLogin st = new StudTutorLogin();
        st.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_loginLinkMouseClicked

    private void logoutLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLinkMouseClicked
        HomePage st = new HomePage();
        st.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutLinkMouseClicked

    private void courseNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseNameTxtActionPerformed
        
    }//GEN-LAST:event_courseNameTxtActionPerformed

    private void previousPageLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousPageLinkMouseClicked
        AdminDashboard st = new AdminDashboard();
        st.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_previousPageLinkMouseClicked

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        HomePage st = new HomePage();
        st.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
     Tutor tt = new Tutor();
     TutorDao dao = new TutorDao();
     
     tt.setEmail(emailTxt.getText());
     String t = dao.deleteTutor(tt);
     if(t!= null){
        JOptionPane.showMessageDialog(this, "Tutor deleted successfully");
        }else{
            JOptionPane.showMessageDialog(this, "Tutor not deleted");
        }
     addTableRowData();
        
    
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        TutorDao dao = new TutorDao();
        Tutor theTutor = new Tutor();
        theTutor.setFullName(fullNameTxt.getText());
        theTutor.setGender(genderCombo.getSelectedItem().toString());
        theTutor.setEmail(emailTxt.getText());
        theTutor.setCourseName(courseNameTxt.getSelectedItem().toString());
        theTutor.setPassword(passwordTxt.getText());
        
        tutor = dao.updateTutor(theTutor);
        if(tutor!= null){
        JOptionPane.showMessageDialog(this, "Tutor updated successfully");
        }else{
            JOptionPane.showMessageDialog(this, " Tutor not updated");
        }
        addTableRowData();
        fullNameTxt.setText(""); 
        genderCombo.setSelectedItem("");
        emailTxt.setText("");
        courseNameTxt.setSelectedItem("");
        passwordTxt.setText("");
    }//GEN-LAST:event_updateBtnActionPerformed

    private void tutorTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutorTableMouseClicked
        /*DefaultTableModel dft = (DefaultTableModel) tutorTable.getModel();
    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(dft);
 
    sorter.setRowFilter(RowFilter.regexFilter(fullNameSearchTxt.getText()));

    tutorTable.setRowSorter(sorter);*/
        
        int row = tutorTable.getSelectedRow();
        TutorDao dao = new TutorDao();
        Tutor tutor =new Tutor();
         Tutor tutorObj = dao.searchTutor(tutor);
            if(tutorObj != null){
                fullNameTxt.setText(tutorObj.getFullName());
                fullNameTxt.setEditable(false);
                genderCombo.setSelectedItem(tutorObj.getGender());
                emailTxt.setText(tutorObj.getEmail());
                courseNameTxt.setSelectedItem(tutorObj.getCourseName());
                passwordTxt.setText(tutorObj.getPassword());
                
            }else{
                JOptionPane.showMessageDialog(this, "Tutor not deleted");
            }
        
        email = tutorTable.getValueAt(row, 3).toString();
        
       
       
        //DefaultTableModel df = (DefaultTableModel) tutorTable.getModel();
        /*int selectedIndex = tutorTable.getSelectedRow();
        
        idtxt.setText(tableModel.getValueAt(selectedIndex, 0).toString());
        fullNameTxt.setText(tableModel.getValueAt(selectedIndex, 1).toString());
        genderCombo.setSelectedItem(tableModel.getValueAt(selectedIndex, 2).toString());
        emailTxt.setText(tableModel.getValueAt(selectedIndex, 3).toString());
        courseNameTxt.setSelectedItem(tableModel.getValueAt(selectedIndex, 4).toString());
        passwordTxt.setText(tableModel.getValueAt(selectedIndex, 5).toString());
       /*Tutor theTutor = new Tutor();
       TutorDao dao = new TutorDao();
       Tutor tutorObj = dao.searchTutor(theTutor);
            if(tutorObj != null){
                passwordTxt.setText(tutorObj.getPassword());
            }else{
                JOptionPane.showMessageDialog(this, "Course doesn't exist");
            }*/
       
    }//GEN-LAST:event_tutorTableMouseClicked

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        DefaultTableModel dft = (DefaultTableModel) tutorTable.getModel();
    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(dft);
 
    sorter.setRowFilter(RowFilter.regexFilter(fullNameSearchTxt.getText()));

    tutorTable.setRowSorter(sorter);
    
    if(fullNameSearchTxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Full Name is Mandatory for searching");
        }else{
            Tutor theTutor = new Tutor();
            theTutor.setFullName(fullNameSearchTxt.getText());
            TutorDao dao = new TutorDao();
            Tutor tutorObj = dao.searchTutor(theTutor);
            if(tutorObj != null){
                fullNameTxt.setText(tutorObj.getFullName());
                //fullNameTxt.setEditable(false);
                genderCombo.setSelectedItem(tutorObj.getGender());
                emailTxt.setText(tutorObj.getEmail());
                courseNameTxt.setSelectedItem(tutorObj.getCourseName());
                passwordTxt.setText(tutorObj.getPassword());
            }else{
                JOptionPane.showMessageDialog(this, "Course doesn't exist");
            }
        }
    
        addTableRowData();
    }//GEN-LAST:event_searchBtnActionPerformed

    private void refreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbtnActionPerformed
        addTableRowData();
    }//GEN-LAST:event_refreshbtnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TutorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TutorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TutorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TutorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TutorForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> courseNameTxt;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField fullNameSearchTxt;
    private javax.swing.JTextField fullNameTxt;
    private javax.swing.JComboBox<String> genderCombo;
    private javax.swing.JTextField idtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loginLink;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel logoutLink;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JLabel previousPageLink;
    private javax.swing.JButton refreshbtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTable tutorTable;
    private javax.swing.JButton tutoregisterBtn;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
